apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grandparent-app
  namespace: test-namespace
spec:
  project: default
  source:
    repoURL: https://github.com/jiaxin-ge/argocd-parent-child-test
    path: parent-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test-namespace
