apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: test-namespace
  labels:
    app.kubernetes.io/instance: grandparent-app
spec:
  project: default
  source:
    repoURL: https://github.com/jiaxin-ge/argocd-parent-child-test
    path: child-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
