apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app
  namespace: test-namespace
  labels:
    app.kubernetes.io/instance: wrong-parent
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    path: helm-guestbook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
